url: "http://alberto-escobar.github.io"

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
